### ISSUE TITLE
Block nonce exceeds MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by zhangyi999** [Qitmeer/qitmeer#116]
The block nonce exceeds the maximum precision security in js and there are two resolution suggestions.

1. When the RPC request returns a nonce field, use the string type, such as:

```js
"nonce": 6277762802949034729 => "nonce": "6277762802949034729"
```

2. When the rpc request returns a nonce field, use the hex type, such as:

```js
"nonce": 6277762802949034729 => "nonce": "571f18021df012e9"
```

**Comment by dindinw** [comment]
1. keep the `nonce` MAX  starting from the `2^53-1` when do the calculation,  as well as to modify the code in the `qitmeer-miner` @jamesvan2019
2. The json marshaller should covert `nonce` to string type.  ex : `strconv.FormatUint(uint64(head.Nonce), 16)}`
see https://github.com/Qitmeer/qitmeer-lib/blob/master/common/marshal/marshal.go#L190
@lochjin

**Comment by dindinw** [comment]
`nonce` is not an issue in the latest code.
