### ISSUE TITLE
Failed to launch after disconnection

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#199]
1. Run
2. Disconnect the network for 1 hour (could be shorter)
3. Reconnect the network 

Observe: no matter how many times tried,  qitmeer failed to launch 

2019-11-29|14:42:37.234 [INFO ] New valid peer: 103.15.132.180:18130 (outbound),user-agent:qitmeer:0.8.2 module=blkmanager
2019-11-29|14:42:37.536 [INFO ] New valid peer: 47.93.20.102:18130 (outbound),user-agent:qitmeer:0.8.2 module=blkmanager
panic: interface conversion: interface {} is blockdag.Empty, not uint

goroutine 25 [running]:
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).updateMainOrder(0xc00049dfb0, 0xc0007a0500, 0x9, 0x10, 0xc000280e78)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:356 +0x63e
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).updateMainChain(0xc00049dfb0, 0xc00055b060, 0xc00055b060, 0xc00055b060)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:287 +0x26f
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).AddBlock(0xc00049dfb0, 0x1a54ea0, 0xc00055b060, 0x0)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:70 +0xb3
github.com/Qitmeer/qitmeer/core/blockdag.(*BlockDAG).AddBlock(0xc0000cc460, 0x1a4a400, 0xc001628000, 0x0)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/blockdag.go:261 +0x6b2
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc0000dc000, 0xc00161e000, 0x0, 0x0, 0x1ecab60)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockchain/accept.go:130 +0x4e4
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc0000dc000, 0xc00161e000, 0xc000000000, 0xc001670000, 0x0, 0x0)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockchain/process.go:177 +0x4d8
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc0001a40e0, 0xc0004a4360)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/handle_block.go:74 +0x27b
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc0001a40e0)
	/Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:512 +0xc9e
created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
	/Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:323 +0xbb

**Comment by forchain** [comment]
reproduced on v0.8.2

**Comment by forchain** [comment]
https://drive.google.com/file/d/1KWqNgqHjvaVO6q8aApCGNbSngSgIIXZ6/view?usp=sharing

**Comment by dindinw** [comment]
need to handle the `Empty` in the `HashSet` of anticone

**Comment by forchain** [comment]
blueDiffAnticone and  redDiffAnticone should use HashMap instead of HashSet, the value of the map should be the local order. The value of HashSet are always empty, so the crash happens whenever blueDiffAnticone and redDiffAnticone are not empty. The reason why it doesn't occur before is that the two sets were always empty because of low concurrency.

**Comment by lochjin** [comment]
> 1. Run
> 2. Disconnect the network for 1 hour (could be shorter)
> 3. Reconnect the network
> 
> Observe: no matter how many times tried, qitmeer failed to launch
> 
> 2019-11-29|14:42:37.234 [INFO ] New valid peer: 103.15.132.180:18130 (outbound),user-agent:qitmeer:0.8.2 module=blkmanager
> 2019-11-29|14:42:37.536 [INFO ] New valid peer: 47.93.20.102:18130 (outbound),user-agent:qitmeer:0.8.2 module=blkmanager
> panic: interface conversion: interface {} is blockdag.Empty, not uint
> 
> goroutine 25 [running]:
> github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).updateMainOrder(0xc00049dfb0, 0xc0007a0500, 0x9, 0x10, 0xc000280e78)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:356 +0x63e
> github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).updateMainChain(0xc00049dfb0, 0xc00055b060, 0xc00055b060, 0xc00055b060)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:287 +0x26f
> github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).AddBlock(0xc00049dfb0, 0x1a54ea0, 0xc00055b060, 0x0)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:70 +0xb3
> github.com/Qitmeer/qitmeer/core/blockdag.(*BlockDAG).AddBlock(0xc0000cc460, 0x1a4a400, 0xc001628000, 0x0)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockdag/blockdag.go:261 +0x6b2
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc0000dc000, 0xc00161e000, 0x0, 0x0, 0x1ecab60)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockchain/accept.go:130 +0x4e4
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc0000dc000, 0xc00161e000, 0xc000000000, 0xc001670000, 0x0, 0x0)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/core/blockchain/process.go:177 +0x4d8
> github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc0001a40e0, 0xc0004a4360)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/handle_block.go:74 +0x27b
> github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc0001a40e0)
> /Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:512 +0xc9e
> created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
> /Users/goldenweek/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:323 +0xbb

https://github.com/Qitmeer/qitmeer/pull/201

**Comment by dindinw** [comment]
fixed by #201
