### ISSUE TITLE
Crash on launching

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#203]
2019-12-02|21:12:03.962 [INFO ] Syncing to state (14225,11463,11489,14313,15) from peer 207.148.95.219:18130 cur graph state:(14182,11432,11458,14267,14) module=blkmanager
panic: interface conversion: interface {} is uint32, not uint [recovered]
	panic: interface conversion: interface {} is uint32, not uint

goroutine 35 [running]:
github.com/Qitmeer/qitmeer/database/ffldb.rollbackOnPanic(0xc0036917a0)
	/home/tony/github.com/Qitmeer/qitmeer/database/ffldb/db.go:1891 +0x77
panic(0xb5c6c0, 0xc0038d3b60)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/Qitmeer/qitmeer/core/blockdag.(*PhantomBlock).Encode(0xc000199bc0, 0xe406e0, 0xc0038d3b30, 0x8, 0xe54d20)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockdag/pantomblock.go:59 +0x646
github.com/Qitmeer/qitmeer/core/blockdag.DBPutDAGBlock(0xe55ba0, 0xc0036917a0, 0xe57c60, 0xc000199bc0, 0x18, 0xb93420)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockdag/dbhelper.go:20 +0x109
github.com/Qitmeer/qitmeer/core/blockchain.(*blockNode).FlushToDB.func1(0xe55ba0, 0xc0036917a0, 0xc0036917a0, 0x0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blocknode.go:402 +0xa6
github.com/Qitmeer/qitmeer/database/ffldb.(*db).Update(0xc0000723c0, 0xc0032ca2a0, 0x0, 0x0)
	/home/tony/github.com/Qitmeer/qitmeer/database/ffldb/db.go:1948 +0xb3
github.com/Qitmeer/qitmeer/core/blockchain.(*blockNode).FlushToDB(0xc003775300, 0xc000446240, 0x0, 0x0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blocknode.go:399 +0x84
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).reorganizeChain(0xc000446240, 0xc00331ade0, 0x3, 0x4, 0xc0038d2480, 0xc00315c930, 0x75, 0xc0036915f0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blockchain.go:1245 +0x347
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).connectDagChain(0xc000446240, 0xc003892900, 0xc00315c930, 0xc0038d2480, 0xc00331ade0, 0x3, 0x4, 0x4, 0x0, 0x0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blockchain.go:975 +0x5e9
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000446240, 0xc00315c930, 0x0, 0x0, 0x12c9ac0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/accept.go:166 +0x76e
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc000446240, 0xc00315c930, 0xc000000000, 0xc0000cc200, 0x0, 0x0)
	/home/tony/github.com/Qitmeer/qitmeer/core/blockchain/process.go:177 +0x4d8
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc00012e0e0, 0xc0038f9710)
	/home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/handle_block.go:74 +0x27b
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc00012e0e0)
	/home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:511 +0xc9e
created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
	/home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:322 +0xbb

block data
[crash.zip](https://github.com/Qitmeer/qitmeer/files/3911427/crash.zip)

**Comment by lochjin** [comment]
> 2019-12-02|21:12:03.962 [INFO ] Syncing to state (14225,11463,11489,14313,15) from peer 207.148.95.219:18130 cur graph state:(14182,11432,11458,14267,14) module=blkmanager
> panic: interface conversion: interface {} is uint32, not uint [recovered]
> panic: interface conversion: interface {} is uint32, not uint
> 
> goroutine 35 [running]:
> github.com/Qitmeer/qitmeer/database/ffldb.rollbackOnPanic(0xc0036917a0)
> /home/tony/github.com/Qitmeer/qitmeer/database/ffldb/db.go:1891 +0x77
> panic(0xb5c6c0, 0xc0038d3b60)
> /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
> github.com/Qitmeer/qitmeer/core/blockdag.(*PhantomBlock).Encode(0xc000199bc0, 0xe406e0, 0xc0038d3b30, 0x8, 0xe54d20)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockdag/pantomblock.go:59 +0x646
> github.com/Qitmeer/qitmeer/core/blockdag.DBPutDAGBlock(0xe55ba0, 0xc0036917a0, 0xe57c60, 0xc000199bc0, 0x18, 0xb93420)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockdag/dbhelper.go:20 +0x109
> github.com/Qitmeer/qitmeer/core/blockchain.(*blockNode).FlushToDB.func1(0xe55ba0, 0xc0036917a0, 0xc0036917a0, 0x0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blocknode.go:402 +0xa6
> github.com/Qitmeer/qitmeer/database/ffldb.(*db).Update(0xc0000723c0, 0xc0032ca2a0, 0x0, 0x0)
> /home/tony/github.com/Qitmeer/qitmeer/database/ffldb/db.go:1948 +0xb3
> github.com/Qitmeer/qitmeer/core/blockchain.(*blockNode).FlushToDB(0xc003775300, 0xc000446240, 0x0, 0x0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blocknode.go:399 +0x84
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).reorganizeChain(0xc000446240, 0xc00331ade0, 0x3, 0x4, 0xc0038d2480, 0xc00315c930, 0x75, 0xc0036915f0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blockchain.go:1245 +0x347
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).connectDagChain(0xc000446240, 0xc003892900, 0xc00315c930, 0xc0038d2480, 0xc00331ade0, 0x3, 0x4, 0x4, 0x0, 0x0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/blockchain.go:975 +0x5e9
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000446240, 0xc00315c930, 0x0, 0x0, 0x12c9ac0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/accept.go:166 +0x76e
> github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc000446240, 0xc00315c930, 0xc000000000, 0xc0000cc200, 0x0, 0x0)
> /home/tony/github.com/Qitmeer/qitmeer/core/blockchain/process.go:177 +0x4d8
> github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc00012e0e0, 0xc0038f9710)
> /home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/handle_block.go:74 +0x27b
> github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc00012e0e0)
> /home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:511 +0xc9e
> created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
> /home/tony/github.com/Qitmeer/qitmeer/services/blkmgr/blkmgr.go:322 +0xbb
> 
> block data
> [crash.zip](https://github.com/Qitmeer/qitmeer/files/3911427/crash.zip)

https://github.com/Qitmeer/qitmeer/pull/202/commits/a79f6624b1b4f052ec54d41b6ea3aded18a0199c

**Comment by forchain** [comment]
verified
