### ISSUE TITLE
Can't start peer because version msg oversized

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer#209]
#### Bug details
The peer failed to start because of the oversized version msg. 
see `func (msg *MsgVersion) MaxPayloadLength(pver uint32) uint32` fuction
#### Screen shot 
![webwxgetmsgimg](https://user-images.githubusercontent.com/1134993/70373262-8f2e9a80-1922-11ea-84e6-05985da928e8.jpeg)

**Comment by lochjin** [comment]
> #### Bug details
> The peer failed to start because of the oversized version msg.
> see `func (msg *MsgVersion) MaxPayloadLength(pver uint32) uint32` fuction
> 
> #### Screen shot
> ![webwxgetmsgimg](https://user-images.githubusercontent.com/1134993/70373262-8f2e9a80-1922-11ea-84e6-05985da928e8.jpeg)



> #### Bug details
> The peer failed to start because of the oversized version msg.
> see `func (msg *MsgVersion) MaxPayloadLength(pver uint32) uint32` fuction
> 
> #### Screen shot
> ![webwxgetmsgimg](https://user-images.githubusercontent.com/1134993/70373262-8f2e9a80-1922-11ea-84e6-05985da928e8.jpeg)


This problem has been fixed:
https://github.com/Qitmeer/qitmeer/commit/d6326d1fb8067c361a4c925919eac8f3212ef5cb

**Comment by dindinw** [comment]
We need more test cases on the `MaxPayloadLength` method of the newly-added/updated msg types: `MsgSyncDAG `, `MsgSyncPoint`, `MsgSyncResult`, `MsgVersion`, to make sure the msg size overflow was not reproduced on the `0.8.4`. 
Please review the code in the `master` branch of those message types to make sure the latest code has no bug hidden.

**Comment by dindinw** [comment]
the commit https://github.com/Qitmeer/qitmeer/commit/74e76b94214e5d7eeda4905ae1ea97e730dc35c6 can be rolled back after the #209 has been fixed.

**Comment by dindinw** [comment]
close the long historical issue
