### ISSUE TITLE
The getRawTransaction could not find the transaction

### ISSUE THREAD

**Issue by bCoder778** [Qitmeer/qitmeer#218]
Some transactions cannot be found by getRawTransaction, but getBlock can find the transaction. And, after a while, the getRawTransaction can be found again.

**Comment by yatingzhou** [comment]
我们也遇到了同样的问题，目前bug已解决

**Comment by dindinw** [comment]
@bCoder778 please report if the issue can be reproduced on the latest qitmeer version ( the version `0.8.4` at the master branch)
