### ISSUE TITLE
How to get CB1~CB4 from blocktemplate

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer#228]
There are CB1, CB2, CB3 and CB4 in the 'NotifyWork struct'. I would like to know how to get these fields from block template, is there any instruction or some part of the code I should read? Thanks.

**Comment by forchain** [comment]
there fields are defined in Qitmeer mining pool protocol  and it is not open sourced.
@5dao please give an introduction of those fields to Ray

**Comment by 5dao** [comment]
end 2019-12-17,qitmeer version 0.8.4 

coinbase split 4 parts 

// cb1 = version + inCount
// cb2 = zeroHashTxRoot + 01 + slen + (blockHeightLen + blockHeight) + (exnonceLen
// cb3 = scriptSigPart2
// cb4 = txInPrevOutIndex + txInSequence + outAmount + outAddr ... + txLockTime + txExpire
//
// coinbaseBuf = cb1 + hash( cb2 + ex1 + ex2 + cb3 ) + cb4

**Comment by rlinxy** [comment]
thanks for sharing this :)

**Comment by rlinxy** [comment]
I am still confused to get those fields from blocktemplate. Is there some document about this part? A specific example would be great. Thanks.

**Comment by PcDeaDZ** [comment]
@5dao can u explain some moments? mining.notify from btc contain only cb1-2 where others? :) wahat is slen? and inCount it its count of transactions?
