### ISSUE TITLE
tips of block is expired

### ISSUE THREAD

**Issue by neal-zhu** [Qitmeer/qitmeer#250]
Guys, I'm developing a qitmeer pool. But when I submit block, I continuously got "tips of block is expired" error from wallet.
Here's my code(adopted from qitmeer-miner):
```go
        subm := hex.EncodeToString(hdata) // hdata is valid HeaderBlock data
        work.bt.Parents is the Parents field from getBlockTemplate api
         subm += Int2varinthex(int64(len(work.bt.Parents)))
         for _, pi := range work.bt.Parents {
             subm += pi.Data
         }
         subm += Int2varinthex(int64(len(work.MerkleBranches)))
         for _, tx := range work.MerkleBranches {
             subm += tx
         }
```
output of qitmeer --version:
```shell
qitmeer version 0.8.4+release-44ff547 (Go version go1.13.4)
```

**Comment by yatingzhou** [comment]
谢谢你提供的意见哦~~~

**Comment by jamesvan2019** [comment]
> Guys, I'm developing a qitmeer pool. But when I submit block, I continuously got "tips of block is expired" error from wallet.
> Here's my code(adopted from qitmeer-miner):
> 
> ```go
>         subm := hex.EncodeToString(hdata) // hdata is valid HeaderBlock data
>         work.bt.Parents is the Parents field from getBlockTemplate api
>          subm += Int2varinthex(int64(len(work.bt.Parents)))
>          for _, pi := range work.bt.Parents {
>              subm += pi.Data
>          }
>          subm += Int2varinthex(int64(len(work.MerkleBranches)))
>          for _, tx := range work.MerkleBranches {
>              subm += tx
>          }
> ```
> 
> output of qitmeer --version:
> 
> ```shell
> qitmeer version 0.8.4+release-44ff547 (Go version go1.13.4)
> ```
listen getBlockTemplate ,if the height is change, it will occur the error

**Comment by dindinw** [comment]
In most cases, it means your mining result is rejected by consensus because you are out of sync with the network. Please make sure you always start your task at the best-synchronized status.

**Comment by dindinw** [comment]
@neal-zhu the issue closed since no reply for a long time, please re-open it if any issue there left.
