### ISSUE TITLE
Send via RPC

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer#252]
Hello there, is there any RPC api we can use to 'send'? Such as 'sendtoaddress' and 'sendmany' of bitcoin. I have read the RPC instruction, but seems we can noly createrawtransaction, sign and send for now. Please let me know. Thanks.

**Comment by dindinw** [comment]
Yes, we only support send signed raw tx by using the `qitmeer`'s RPC. by this way, the node never handles your private-key.
1.) you can do it by yourself like `bitcoin-cli` did.
2.) use the `qitmeer-wallet`'s RPC.  (not well-maintained for now), see https://github.com/qitmeer/qitmeer-wallet
PR is welcomed if you are interested in improving `qitmeer-wallet`

**Comment by dindinw** [comment]
@rlinxy the issue is closed since no-reply for a long time, please re-open it if you have any issue or idea on this topic. thanks.
