### ISSUE TITLE
getBlockHash returns the hash of the block with the same 'order'

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer#253]
I think getBlockHash should return the hash of the block of specific 'height'
For instance
getBlockHash 60000
should return the hash of block 60000.

**Comment by rlinxy** [comment]
> ./qitmeer-cli -u qitmeer -P 123456 getBlockhash 68110
> 1c742ce1cc261b00322e9ba7da3b3973068260ce9629779c731714b73e3baa03
> 
> ./qitmeer-cli -u qitmeer -P 123456 getBlock 68110
> {"hash":"1c742ce1cc261b00322e9ba7da3b3973068260ce9629779c731714b73e3baa03","txsvalid":true,"confirmations":13575,"version":10,"weight":488,"height":54548,"txRoot":"f19c9548df589fa8bbb48e69922d400c3d011e2bf10bb88388a19246f27234cd","order":68110,"transactions":[{"hex":"010000000170f8ebbca8cbc374fe6b60fc11905e874afdbe8dd53038b5420eaba9f298d70cffffffffffffffff0100216e83010000001976a914c4c98d3b8d80acb9f3fdf113266d476cf779c80988ac000000000000000001520314d50008841eb972499988a41f456c766973204e6f64653031353831343232313535303737353039393737322435643365356133352d646438332d343436362d616330652d343462646561616230393534","txid":"f19c9548df589fa8bbb48e69922d400c3d011e2bf10bb88388a19246f27234cd","txhash":"89bfce143b279d4a94307f405d166922c84b7fd56f5b90fa3553d0a41b14747c","size":172,"version":1,"locktime":0,"expire":0,"vin":[{"coinbase":"0314d50008841eb972499988a41f456c766973204e6f64653031353831343232313535303737353039393737322435643365356133352d646438332d343436362d616330652d343462646561616230393534","sequence":4294967295}],"vout":[{"amount":6500000000,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 c4c98d3b8d80acb9f3fdf113266d476cf779c809 OP_EQUALVERIFY OP_CHECKSIG","hex":"76a914c4c98d3b8d80acb9f3fdf113266d476cf779c80988ac","reqSigs":1,"type":"pubkeyhash","addresses":["TmgtbbazEm6b28cjQeC8coMEpHUGpWSywTG"]}}],"blockhash":"1c742ce1cc261b00322e9ba7da3b3973068260ce9629779c731714b73e3baa03","confirmations":13575}],"stateRoot":"0000000000000000000000000000000000000000000000000000000000000000","bits":"20d9b00","difficulty":34446080,"pow":{"pow_name":"cuckaroo","pow_type":1,"nonce":168,"proof_data":{"edge_bits":29,"circle_nonces":"44de2900696b6f00463e8c005c18ca00bcc1fd01555d0504a8ad3304a67544042c33480452cfe404dac71e06fe507f061fd413077c1eca071ae747083f1f590908471c0a43a21c0b02e1a00b7a70400cb9a0080e8b61190e82d6a60e5344790f0659dd0f9c79391009bd9c123365731315ea971309233017cba4471765cab817160ef51758801018deca98188e17321a904df41a554b651cc63a741cbfdbe91c1ec3c11ec69cec1f"}},"timestamp":"2019-12-27T07:41:16+08:00","parentroot":"5cbd6fb68295e47426aedeb29500c44a26fb3f70d6800f408f9adc96db0a51a8","parents":["5cbd6fb68295e47426aedeb29500c44a26fb3f70d6800f408f9adc96db0a51a8"],"children":["46dd399330b83d73c49d091458e6b43d2143dd0cdf509ce0729c415ee50d6e1f"]}

**Comment by dindinw** [comment]
@rlinxy would u mind open the issue at https://github.com/Qitmeer/qitmeer-cli ?
it is maintained separately with the `qitmeer` backend.  
@5dao can you look into the issue. ?
@rlinxy  you might want to try `script/cli.sh`

**Comment by 5dao** [comment]
> I think getBlockHash should return the hash of the block of specific 'height'
> For instance
> getBlockHash 60000
> should return the hash of block 60000.

qitmeer blocks base on DAG,so there are height and order,

getBlock {orderNumber},not height

please see qitmeer-cli -h

**Comment by rlinxy** [comment]
well, but can we have the 'getBlockByHeight' API same as ETH?

**Comment by 5dao** [comment]
> well, but can we have the 'getBlockByHeight' API same as ETH?

yes,you can't ,you can getblock by block's order.

`
    getBlockCount           
	getBlockTotal       
	getOrphansTotal     
	getBlockHash        
	getBlock            
	getBlockHashByRange 
	getBlockByOrder     
	getBlockByID        
	getBestBlockHash    
	getBlockHeader      
	isOnMainChain       
	getMainChainHeight  
	getBlockWeight      
	isBlue
`
