### ISSUE TITLE
Is there RPC api to validate address?

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer#264]
Hi there,

We went through the dev document of the node, but couldn't find an API to tell if an address is valid or not. I am wondering is there any API we can use as 'validateaddress'  from Bitcoin? Thanks.

**Comment by jamesvan2019** [comment]
https://github.com/Qitmeer/qitmeer/tree/master/cmd/qx    you can compile qx tools for creating tbe right address

**Comment by rlinxy** [comment]
Actually what I need is to validate an address, for instance to tell if the address 'aaabbbccc' is the valid Pmeer address or not. I don't see the qx tools can do this, is there any document about this? Thanks.

**Comment by dindinw** [comment]
```
qx base58check-decode aaabbbccc
Qx Error : "checksum error"
```

```
qx base58check-decode TmYFQGAXtF3KeBG962kimzMtcTQyj6njrcA
65ffb166a5eb252285b207a5639f97f9dbc42dfb
```

**Comment by dindinw** [comment]
@rlinxy  #296 has merged, you can test it by pulling the latest code from the 0.9.0-dev branch. see a curl example showing how to use the API from the https://github.com/Qitmeer/qitmeer/pull/296
