### ISSUE TITLE
getRawTransaction return no information available about transaction

### ISSUE THREAD

**Issue by Noctis0227** [Qitmeer/qitmeer#294]
txid: 248c25978f089bbc06737e40566c865e3ddeb920976b6fbe3dc42e00593f1ab7
qitmeer version: qitmeer version 0.8.5+release-c123ce6 (Go version go1.13.4)
node data: https://drive.google.com/open?id=1UZoGzOZKLokmM1-SgZ6V1CEuZBovTIC6

**Comment by Noctis0227** [comment]
https://drive.google.com/open?id=18rTi7_OyuL-Oug4QKmdCT8Le0ULKwZBs

**Comment by dindinw** [comment]
ACK the issue by using the later data provided by the above link. (The first link contains corrected data, DON'T use).  The `getRrawTansaction` PRC can't find the tx, but getBlockOrder 401682 confirm the tx `248c25978f089bbc06737e40566c865e3ddeb920976b6fbe3dc42e00593f1ab7` 's existing. The data-inconsist of the txindex database with the block database may occur.

**Comment by dindinw** [comment]
@Noctis0227  please use `'--troptxindex'` to replace the `'--txindex'` option to restart your server( it will delete all corrupted index data). then restart the server by using the '--txindex'.  Wait for several minutes until the server rebuilds your tx index database successfully. let me know if the workaround works for you.

**Comment by lochjin** [comment]
If need txindex,you must use the latest version.
