### ISSUE TITLE
I can't start it

### ISSUE THREAD

**Issue by wzt-tao** [Qitmeer/qitmeer#311]
version qitmeer version 0.8.5+release-c123ce6 (Go version go1.13.4)
./qitmeer --testnet --notls --rpcuser=test --rpcpass=test --nodnss
eed
![image](https://user-images.githubusercontent.com/53932327/85093412-cb6e7c00-b21e-11ea-8659-f0934ae7e198.png)

**Comment by dindinw** [comment]
I think it had already been started. you might add `-d debug` to print more information.

**Comment by dindinw** [comment]
@wzt-tao closed since no further inputs. Please reopen it if any issue.
