### ISSUE TITLE
非挖矿节点，偶尔就会比其他节点同步慢几百个order

### ISSUE THREAD

**Issue by zhangcongrong** [Qitmeer/qitmeer#328]
1. version: qitmeer version 0.9.0+release-9196b40 (Go version go1.14.4)
2. 节点一直在重复 adding 和 sending
![image](https://user-images.githubusercontent.com/15316827/86067459-83b1e500-baa7-11ea-8025-cf35c4fbedc9.png)

3. 这个节点只是被用来做 rpc 服务的，也就是说，有服务在请求这个节点的rpc服务

**Comment by dindinw** [comment]
@zhangcongrong  please try the latest pre-release version`0.9.1-alpha` https://github.com/Qitmeer/qitmeer/releases

**Comment by dindinw** [comment]
@zhangcongrong  The qitmeer version of 0.9.1 has been released, I believe issue 328 has been fixed. please try the latest stable version https://github.com/Qitmeer/qitmeer/releases/tag/v0.9.1-release.  the issue is closed for now, Please reopen it if any problem.
