### ISSUE TITLE
Kafh钱包转账一直处于未确认状态

### ISSUE THREAD

**Issue by zhangcongrong** [Qitmeer/qitmeer#342]
1. 使用Kahf钱包第一次转账50000到另一个钱包,正常，提示“等待确认”；
2.第二次继续转账50000，提示“请联系管理员”；
3. 第三次转账45000，显示正常，提示“等待确认”；
4. 第四次转账45000，显示正常，提示“等待确认”；
5. 最后，只有第一笔确认了，转账成功；其他都是“未确认”状态
6. 钱包余额少了 50000+50000+45000+45000

![image](https://user-images.githubusercontent.com/15316827/88472803-5ee74b00-cf49-11ea-9660-39b577ffa33a.png)

**Comment by dindinw** [comment]
@zhangcongrong 
if it's a usage issue of the kafh wallet, Please open the issue at https://github.com/kahf-io 
if you are doubt about an invalid tx, Please open issue at https://github.com/Qitmeer/0.9.1-invalid-utxo/issues. and provide the tx_id you doubt.
