### ISSUE TITLE
TestWsNotify

### ISSUE THREAD

**Issue by lochjin** [Qitmeer/qitmeer#461]
The use of these two places is inconsistent. Inside is map (https://github.com/Qitmeer/qitmeer/blob/0.10-dev/testutils/testwallet.go#L78), but outside is array (https://github.com/Qitmeer/qitmeer/blob/0.10-dev/testutils/ws_test.go#L50)
error message:
https://travis-ci.com/github/Qitmeer/qitmeer/builds/222050277#L726

**Comment by dindinw** [comment]
fixed by #462
