### ISSUE TITLE
RPCFilterAdd error

### ISSUE THREAD

**Issue by bCoder778** [Qitmeer/qitmeer#487]
failed to marshal for type: qitmeer_p2p_v1.FilterLoadRequest: unsupported kind: int64

RPCFilterAdd param qitmeer_p2p_v1.FilterLoadRequest ：

`func NewFilterLoadRequest() *qitmeer_p2p_v1.FilterLoadRequest {`
	`rand.Seed(time.Now().UnixNano())`
	`tweak := rand.Uint32()`
	`f := bloom.NewFilter(10, tweak, 0.0001, types.BloomUpdateNone)`
	`return &qitmeer_p2p_v1.FilterLoadRequest{`
		`Filter:    f.MsgFilterLoad().Filter,`
		`HashFuncs: int64(f.MsgFilterLoad().HashFuncs),`
		`Tweak:     int64(f.MsgFilterLoad().Tweak),`
		`Flags:     int64(f.MsgFilterLoad().Flags),`
	`}`
`}`

**Comment by dindinw** [comment]
@jamesvan2019  looks like the obsoleted gPRC/protobuffer generated code? Please check if the `proto` file is matched with the generated go code.

**Comment by jamesvan2019** [comment]
okay,I will track this issue.
