### ISSUE TITLE
Send transaction to 0.10, node crashed

### ISSUE THREAD

**Issue by bCoder778** [Qitmeer/qitmeer#499]
rawtransaction:010000000002000000943577000000001976a914cec9c6fb443a62b5e8d7a00fc3ad0f3cef1f070588ac000000c5015a020000001976a914807b61617f12c3166f4531ddeae484b82187ae2f88acfb1c0000000000007fc4be6000

panic: runtime error: index out of range [0] with length 0

goroutine 147 [running]:
github.com/Qitmeer/qitmeer/core/types.IsTokenMintTx(...)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/core/types/txtype.go:235
github.com/Qitmeer/qitmeer/core/types.DetermineTxType(0xc0005f9680, 0x6)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/core/types/txtype.go:99 +0x371
github.com/Qitmeer/qitmeer/core/blockchain.CheckTransactionSanity(0xc0005f9680, 0x2925180, 0xc003a88bc8, 0x2980360)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/core/blockchain/validate.go:293 +0x45
github.com/Qitmeer/qitmeer/services/mempool.(*TxPool).maybeAcceptTransaction(0xc000804000, 0xc003a88bc0, 0x1, 0x1c30520, 0x278fa20, 0x27e5ca0, 0x4, 0x4, 0x55967213dd)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/services/mempool/mempool.go:211 +0xb5
github.com/Qitmeer/qitmeer/services/mempool.(*TxPool).ProcessTransaction(0xc000804000, 0xc003a88bc0, 0xc000000000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/services/mempool/mempool.go:596 +0x126
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc0005aaa90)
	/Users/baixiaoliang/Documents/GitHub/qitmeer/services/blkmgr/blkmgr.go:412 +0xc82
created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
	/Users/baixiaoliang/Documents/GitHub/qitmeer/services/blkmgr/blkmgr.go:284 +0xbc

**Comment by dindinw** [comment]
fixed by #500
