### ISSUE TITLE
昨天社区反馈的问题

### ISSUE THREAD

**Issue by bbkbk222** [Qitmeer/qitmeer#545]
1 节点无法联网 杀毒工具已经关闭 重启多次，联通网络
2挖矿工具持续掉算力
3实际收到的币和挖矿工具显示的不符合
4钱包挖到的币会显示失败

**Comment by bbkbk222** [comment]
![fd2d3269b833b94361cd6ecce58545b](https://user-images.githubusercontent.com/48194218/127728937-ae100a34-c8bc-494d-855e-99745e671787.jpg)

**Comment by dindinw** [comment]
@bbkbk222 The qitmeer repo is for the backend issue only. the `kafh wallet` issue please consult the official support of the wallet.
