### ISSUE TITLE
Block synchronization is slow

### ISSUE THREAD

**Issue by luoshan654** [Qitmeer/qitmeer#58]
The synchronization of 3000 blocks is very slow, and the two-day time synchronization is not complete. At present, the height of observation blocks will be very long at 377 hours.
The connection node is 47.103.194.115:18130.

**Comment by dindinw** [comment]
upgrade to version 0.6.2 should fix it. see #107

**Comment by dindinw** [comment]
the issue has been fixed since 0.6.2
