### ISSUE TITLE
Qitmeer 0.10.6 is the main network? After I use the Windows version, I created the testnet folder? Is that normal?

### ISSUE THREAD

**Issue by 1617176084** [Qitmeer/qitmeer#686]

**Comment by dindinw** [comment]
The 0.10.6 windows version has a bug in the `start.bat` script (which works for windows version only).  https://github.com/Qitmeer/qitmeer/blob/0.10.6-rel/script/win/start.bat#L20
which means the network is set to testnet by default. For a quick fix, please modify `config.conf` file, to remove the line `testnet=true` or delete the file directly, it should also work.

**Comment by 1617176084** [comment]
![image](https://user-images.githubusercontent.com/7008899/144212903-cf54d8d4-8a48-4bd9-95ad-f23b7a423b09.png)
Is the main network officially up and running? I have been trying to show the link status for a long time and cannot download the correct node on the database connection

**Comment by dindinw** [comment]
Please make sure 
- check your P2P port, test if it has been blocked? (check your `conf` file for the port you are using or use `./qitmeer --help` command to find the default P2P port) If you are behind a firework, please make sure to modify your firewall rule to allow the port.
-  for a better connection experience and time-saving, Please use a cloud machine to setup your `qitmeer` full node. The node without opening the P2P port might be suffering a slow connection and sync.
- If you still want to setup a windows node on your laptop, you can try 1+1 mode, which means 1 cloud node + 1 laptop node, at the same time, configure the white-list setting to add your own laptop node on the cloud node (see `qitmeer --help` for details). by this way, you can keep a good connection at the same time without opening the P2P port on your laptop. (Note, Please remember your always have to open P2P port on your cloud node, it's the key to get good connection and sync speed.)
