### ISSUE TITLE
performance tests: mempool has a lot of transactions, but getBlockTemplate RPC method can't get any transaction. 

### ISSUE THREAD

**Issue by eric7733** [Qitmeer/qitmeer#83]
When performing a performance test,  sending 10,000 transactions in 1 minute, mempool has a lot of transactions. However, miner can't get any transaction in the mempool. getBlockTemplate RPC method also can't get any transaction. 
![image](https://user-images.githubusercontent.com/48508289/62878996-c7e7aa00-bd5c-11e9-8e99-f9bcfd170d61.png)
![image](https://user-images.githubusercontent.com/48508289/62879021-d2a23f00-bd5c-11e9-9f52-df2b6d9d9c2e.png)
![image](https://user-images.githubusercontent.com/48508289/62879038-da61e380-bd5c-11e9-8e32-7a5d24da9555.png)
![image](https://user-images.githubusercontent.com/48508289/62879048-e0f05b00-bd5c-11e9-84a4-a3c2a24192ec.png)

**Comment by jamesvan2019** [comment]
This issue had fixed, if GBT have many transactions,you can set --blockmaxsize when start qitmeer to control the tx count.
the  blockmaxsize is the maximum block size in bytes to be used when generating a block template.

**Comment by dindinw** [comment]
the issue has been fixed by the lastest code.
