### ISSUE TITLE
block sync problem

### ISSUE THREAD

**Issue by eric7733** [Qitmeer/qitmeer#84]
The first 4677 blocks are synchronized quickly, but the last block 4678 has been unable to synchronize. 

Calling getBlockTemplate RPC to get the following info:
![image](https://user-images.githubusercontent.com/48508289/63208999-fa532780-c10d-11e9-99fa-4d40a70632cd.png)

Calling getBlockCount RPC to get the following info:
![image](https://user-images.githubusercontent.com/48508289/63208984-ca0b8900-c10d-11e9-8e09-47ab015fe50f.png)

Calling getPeerInfo RPC to get the following info:
It's very strange, getPeerInfo RPC and getBlockCount RPC show different results.
![image](https://user-images.githubusercontent.com/48508289/63208957-7600a480-c10d-11e9-977b-5de3f72d3ba5.png)

**Comment by dindinw** [comment]
#107 #58
